
let kUTTypeItem: CFString
let kUTTypeContent: CFString
let kUTTypeCompositeContent: CFString
let kUTTypeMessage: CFString
let kUTTypeContact: CFString
let kUTTypeArchive: CFString
let kUTTypeDiskImage: CFString
let kUTTypeData: CFString
let kUTTypeDirectory: CFString
let kUTTypeResolvable: CFString
let kUTTypeSymLink: CFString
let kUTTypeExecutable: CFString
let kUTTypeMountPoint: CFString
let kUTTypeAliasFile: CFString
let kUTTypeAliasRecord: CFString
let kUTTypeURLBookmarkData: CFString
let kUTTypeURL: CFString
let kUTTypeFileURL: CFString
let kUTTypeText: CFString
let kUTTypePlainText: CFString
let kUTTypeUTF8PlainText: CFString
let kUTTypeUTF16ExternalPlainText: CFString
let kUTTypeUTF16PlainText: CFString
let kUTTypeDelimitedText: CFString
let kUTTypeCommaSeparatedText: CFString
let kUTTypeTabSeparatedText: CFString
let kUTTypeUTF8TabSeparatedText: CFString
let kUTTypeRTF: CFString
let kUTTypeHTML: CFString
let kUTTypeXML: CFString
let kUTTypeSourceCode: CFString
let kUTTypeAssemblyLanguageSource: CFString
let kUTTypeCSource: CFString
let kUTTypeObjectiveCSource: CFString
let kUTTypeSwiftSource: CFString
let kUTTypeCPlusPlusSource: CFString
let kUTTypeObjectiveCPlusPlusSource: CFString
let kUTTypeCHeader: CFString
let kUTTypeCPlusPlusHeader: CFString
let kUTTypeJavaSource: CFString
let kUTTypeScript: CFString
let kUTTypeAppleScript: CFString
let kUTTypeOSAScript: CFString
let kUTTypeOSAScriptBundle: CFString
let kUTTypeJavaScript: CFString
let kUTTypeShellScript: CFString
let kUTTypePerlScript: CFString
let kUTTypePythonScript: CFString
let kUTTypeRubyScript: CFString
let kUTTypePHPScript: CFString
let kUTTypeJSON: CFString
let kUTTypePropertyList: CFString
let kUTTypeXMLPropertyList: CFString
let kUTTypeBinaryPropertyList: CFString
let kUTTypePDF: CFString
let kUTTypeRTFD: CFString
let kUTTypeFlatRTFD: CFString
let kUTTypeTXNTextAndMultimediaData: CFString
let kUTTypeWebArchive: CFString
let kUTTypeImage: CFString
let kUTTypeJPEG: CFString
let kUTTypeJPEG2000: CFString
let kUTTypeTIFF: CFString
let kUTTypePICT: CFString
let kUTTypeGIF: CFString
let kUTTypePNG: CFString
let kUTTypeQuickTimeImage: CFString
let kUTTypeAppleICNS: CFString
let kUTTypeBMP: CFString
let kUTTypeICO: CFString
let kUTTypeRawImage: CFString
let kUTTypeScalableVectorGraphics: CFString
let kUTTypeAudiovisualContent: CFString
let kUTTypeMovie: CFString
let kUTTypeVideo: CFString
let kUTTypeAudio: CFString
let kUTTypeQuickTimeMovie: CFString
let kUTTypeMPEG: CFString
let kUTTypeMPEG2Video: CFString
let kUTTypeMPEG2TransportStream: CFString
let kUTTypeMP3: CFString
let kUTTypeMPEG4: CFString
let kUTTypeMPEG4Audio: CFString
let kUTTypeAppleProtectedMPEG4Audio: CFString
let kUTTypeAppleProtectedMPEG4Video: CFString
let kUTTypeAVIMovie: CFString
let kUTTypeAudioInterchangeFileFormat: CFString
let kUTTypeWaveformAudio: CFString
let kUTTypeMIDIAudio: CFString
let kUTTypePlaylist: CFString
let kUTTypeM3UPlaylist: CFString
let kUTTypeFolder: CFString
let kUTTypeVolume: CFString
let kUTTypePackage: CFString
let kUTTypeBundle: CFString
let kUTTypePluginBundle: CFString
let kUTTypeSpotlightImporter: CFString
let kUTTypeQuickLookGenerator: CFString
let kUTTypeXPCService: CFString
let kUTTypeFramework: CFString
let kUTTypeApplication: CFString
let kUTTypeApplicationBundle: CFString
let kUTTypeApplicationFile: CFString
let kUTTypeUnixExecutable: CFString
let kUTTypeWindowsExecutable: CFString
let kUTTypeJavaClass: CFString
let kUTTypeJavaArchive: CFString
let kUTTypeSystemPreferencesPane: CFString
let kUTTypeGNUZipArchive: CFString
let kUTTypeBzip2Archive: CFString
let kUTTypeZipArchive: CFString
let kUTTypeSpreadsheet: CFString
let kUTTypePresentation: CFString
let kUTTypeDatabase: CFString
let kUTTypeVCard: CFString
let kUTTypeToDoItem: CFString
let kUTTypeCalendarEvent: CFString
let kUTTypeEmailMessage: CFString
let kUTTypeInternetLocation: CFString
let kUTTypeInkText: CFString
let kUTTypeFont: CFString
let kUTTypeBookmark: CFString
let kUTType3DContent: CFString
let kUTTypePKCS12: CFString
let kUTTypeX509Certificate: CFString
let kUTTypeElectronicPublication: CFString
let kUTTypeLog: CFString
let kUTExportedTypeDeclarationsKey: CFString
let kUTImportedTypeDeclarationsKey: CFString
let kUTTypeIdentifierKey: CFString
let kUTTypeTagSpecificationKey: CFString
let kUTTypeConformsToKey: CFString
let kUTTypeDescriptionKey: CFString
let kUTTypeIconFileKey: CFString
let kUTTypeReferenceURLKey: CFString
let kUTTypeVersionKey: CFString
let kUTTagClassFilenameExtension: CFString
let kUTTagClassMIMEType: CFString
func UTTypeCreatePreferredIdentifierForTag(inTagClass: CFString, _ inTag: CFString, _ inConformingToUTI: CFString?) -> Unmanaged<CFString>?
func UTTypeCreateAllIdentifiersForTag(inTagClass: CFString, _ inTag: CFString, _ inConformingToUTI: CFString?) -> Unmanaged<CFArray>?
func UTTypeCopyPreferredTagWithClass(inUTI: CFString, _ inTagClass: CFString) -> Unmanaged<CFString>?
func UTTypeCopyAllTagsWithClass(inUTI: CFString, _ inTagClass: CFString) -> Unmanaged<CFArray>?
func UTTypeEqual(inUTI1: CFString, _ inUTI2: CFString) -> Bool
func UTTypeConformsTo(inUTI: CFString, _ inConformsToUTI: CFString) -> Bool
func UTTypeCopyDescription(inUTI: CFString) -> Unmanaged<CFString>?
func UTTypeIsDeclared(inUTI: CFString) -> Bool
func UTTypeIsDynamic(inUTI: CFString) -> Bool
func UTTypeCopyDeclaration(inUTI: CFString) -> Unmanaged<CFDictionary>?
func UTTypeCopyDeclaringBundleURL(inUTI: CFString) -> Unmanaged<CFURL>?
